// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScientificReport.DAL.DbContext;

namespace ScientificReport.Migrations
{
    [DbContext(typeof(ScientificReportDbContext))]
    [Migration("20190604201756_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ApplicantsPatentLicenseActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ApplicantId");

                    b.Property<Guid>("PatentLicenseActivityId");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("PatentLicenseActivityId");

                    b.ToTable("ApplicantsPatentLicenseActivities");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.AuthorsPatentLicenseActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId");

                    b.Property<Guid>("PatentLicenseActivityId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PatentLicenseActivityId");

                    b.ToTable("AuthorsPatentLicenseActivities");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.CoApplicantsPatentLicenseActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoApplicant");

                    b.Property<Guid>("PatentLicenseActivityId");

                    b.HasKey("Id");

                    b.HasIndex("PatentLicenseActivityId");

                    b.ToTable("CoApplicantsPatentLicenseActivities");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.CoauthorsPatentLicenseActivities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Coauthor");

                    b.Property<Guid>("PatentLicenseActivityId");

                    b.HasKey("Id");

                    b.HasIndex("PatentLicenseActivityId");

                    b.ToTable("CoauthorsPatentLicenseActivities");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Conference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<Guid?>("DepartmentReportId");

                    b.Property<string>("Topic");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentReportId");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("HeadId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Grant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Info");

                    b.HasKey("Id");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MembershipInfo");

                    b.Property<int>("Type");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Opposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<DateTime>("DateOfOpposition");

                    b.Property<Guid?>("OpponentId");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.ToTable("Oppositions");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.PatentLicenseActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<int>("Number");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("PatentLicenseActivities");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.PostgraduateDissertationGuidance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateDegreeGained");

                    b.Property<string>("Dissertation");

                    b.Property<int>("GraduationYear");

                    b.Property<Guid?>("GuideId");

                    b.Property<string>("PostgraduateName");

                    b.Property<string>("Speciality");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("PostgraduateDissertationGuidances");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.PostgraduateGuidance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GuideId");

                    b.Property<string>("PostgraduateInfo");

                    b.Property<string>("PostgraduateName");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("PostgraduateGuidances");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Publications.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ArticleType");

                    b.Property<string>("DocumentInfo");

                    b.Property<bool>("IsPeriodical");

                    b.Property<bool>("IsPrintCanceled");

                    b.Property<bool>("IsRecommendedToPrint");

                    b.Property<string>("LiabilityInfo");

                    b.Property<int>("Number");

                    b.Property<int>("PagesAmount");

                    b.Property<string>("PublishingHouseName");

                    b.Property<string>("PublishingPlace");

                    b.Property<int>("PublishingYear");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Publications.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PagesAmount");

                    b.Property<int>("PrintStatus");

                    b.Property<int>("PublicationType");

                    b.Property<string>("PublishingHouseName");

                    b.Property<string>("PublishingPlace");

                    b.Property<int>("PublishingYear");

                    b.Property<string>("Specification");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Publications.ScientificWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<string>("Contents");

                    b.Property<string>("Cypher");

                    b.Property<Guid?>("DepartmentId");

                    b.Property<int>("PublishingYear");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("ScientificWorks");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ReportThesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ConferenceId");

                    b.Property<string>("Thesis");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.ToTable("ReportTheses");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.DepartmentReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Edited");

                    b.Property<Guid?>("FacultyReportId");

                    b.Property<Guid?>("HeadOfDepartmentId");

                    b.HasKey("Id");

                    b.HasIndex("FacultyReportId");

                    b.HasIndex("HeadOfDepartmentId");

                    b.ToTable("DepartmentReports");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.FacultyReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AdministratorId");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Edited");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId");

                    b.ToTable("FacultyReports");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("DepartmentReportId");

                    b.Property<DateTime>("Edited");

                    b.Property<Guid?>("TeacherId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentReportId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherReports");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsArticles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ArticleId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsArticles");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsGrants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("GrantId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsGrants");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsMemberships", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MembershipId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsMemberships");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsOppositions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("OppositionId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("OppositionId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsOppositions");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPatents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PatentId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("PatentId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsPatents");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPostgraduateDissertationGuidances", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PostgraduateDissertationGuidanceId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("PostgraduateDissertationGuidanceId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsPostgraduateDissertationGuidances");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPostgraduateGuidances", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PostgraduateGuidanceId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("PostgraduateGuidanceId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsPostgraduateGuidances");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPublications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("PublicationId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsPublications");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsReportThesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ReportThesisId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("ReportThesisId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsReportThesis");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsReviews", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ReviewId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsReviews");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsScientificConsultations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ScientificConsultationId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("ScientificConsultationId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsScientificConsultations");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsScientificInternships", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ScientificInternshipId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("ScientificInternshipId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsScientificInternships");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsScientificWorks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ScientificWorkId");

                    b.Property<Guid?>("TeacherReportId");

                    b.HasKey("Id");

                    b.HasIndex("ScientificWorkId");

                    b.HasIndex("TeacherReportId");

                    b.ToTable("TeacherReportsScientificWorks");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfReview");

                    b.Property<Guid?>("ReviewerId");

                    b.Property<Guid?>("WorkId");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("WorkId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ScientificConsultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CandidateName");

                    b.Property<string>("DissertationTitle");

                    b.Property<Guid?>("GuideId");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("ScientificConsultations");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ScientificInternship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contents");

                    b.Property<DateTime>("Ended");

                    b.Property<string>("PlaceOfInternship");

                    b.Property<DateTime>("Started");

                    b.HasKey("Id");

                    b.ToTable("ScientificInternships");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcademicStatus");

                    b.Property<int>("AccessFailedCount");

                    b.Property<int>("BirthYear");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<Guid?>("DepartmentId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<int>("GraduationYear");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("MiddleName");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Position");

                    b.Property<string>("ScientificDegree");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Sex");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<int>("YearDegreeAssigned");

                    b.Property<int>("YearDegreeGained");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesArticles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ArticleId");

                    b.Property<Guid>("AuthorId");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.ToTable("UserProfilesArticles");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesGrants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("GrantId");

                    b.Property<Guid>("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("GrantId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfilesGrants");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesPublications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PublicationId");

                    b.Property<Guid>("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfilesPublications");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesReportThesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ReportThesisId");

                    b.Property<Guid?>("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ReportThesisId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfilesReportTheses");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesScientificInternships", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ScientificInternshipId");

                    b.Property<Guid>("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ScientificInternshipId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfilesScientificInternships");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesScientificWorks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ScientificWorkId");

                    b.Property<Guid?>("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ScientificWorkId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserProfilesScientificWorks");
                });

            modelBuilder.Entity("ScientificReport.DAL.Roles.UserProfileRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ScientificReport.DAL.Roles.UserProfileRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ScientificReport.DAL.Roles.UserProfileRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ApplicantsPatentLicenseActivities", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Applicant")
                        .WithMany("ApplicantsPatentLicenseActivities")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.PatentLicenseActivity", "PatentLicenseActivity")
                        .WithMany("ApplicantsPatentLicenseActivities")
                        .HasForeignKey("PatentLicenseActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.AuthorsPatentLicenseActivities", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Author")
                        .WithMany("AuthorsPatentLicenseActivities")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.PatentLicenseActivity", "PatentLicenseActivity")
                        .WithMany("AuthorsPatentLicenseActivities")
                        .HasForeignKey("PatentLicenseActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.CoApplicantsPatentLicenseActivities", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.PatentLicenseActivity", "PatentLicenseActivity")
                        .WithMany("CoApplicantsPatentLicenseActivities")
                        .HasForeignKey("PatentLicenseActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.CoauthorsPatentLicenseActivities", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.PatentLicenseActivity", "PatentLicenseActivity")
                        .WithMany("CoauthorsPatentLicenseActivities")
                        .HasForeignKey("PatentLicenseActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Conference", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Reports.DepartmentReport")
                        .WithMany("Conferences")
                        .HasForeignKey("DepartmentReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Department", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Membership", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Opposition", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Opponent")
                        .WithMany()
                        .HasForeignKey("OpponentId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.PostgraduateDissertationGuidance", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.PostgraduateGuidance", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Publications.ScientificWork", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Department")
                        .WithMany("ScientificWorks")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ReportThesis", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.DepartmentReport", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Reports.FacultyReport")
                        .WithMany("DepartmentReports")
                        .HasForeignKey("FacultyReportId");

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "HeadOfDepartment")
                        .WithMany()
                        .HasForeignKey("HeadOfDepartmentId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.FacultyReport", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReport", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Reports.DepartmentReport")
                        .WithMany("TeacherReports")
                        .HasForeignKey("DepartmentReportId");

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsArticles", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Publications.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsArticles")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsGrants", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Grant", "Grant")
                        .WithMany()
                        .HasForeignKey("GrantId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsGrants")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsMemberships", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsMemberships")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsOppositions", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Opposition", "Opposition")
                        .WithMany()
                        .HasForeignKey("OppositionId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsOppositions")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPatents", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.PatentLicenseActivity", "Patent")
                        .WithMany()
                        .HasForeignKey("PatentId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsPatents")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPostgraduateDissertationGuidances", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.PostgraduateDissertationGuidance", "PostgraduateDissertationGuidance")
                        .WithMany()
                        .HasForeignKey("PostgraduateDissertationGuidanceId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsPostgraduateDissertationGuidances")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPostgraduateGuidances", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.PostgraduateGuidance", "PostgraduateGuidance")
                        .WithMany()
                        .HasForeignKey("PostgraduateGuidanceId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsPostgraduateGuidances")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsPublications", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Publications.Publication", "Publication")
                        .WithMany()
                        .HasForeignKey("PublicationId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsPublications")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsReportThesis", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.ReportThesis", "ReportThesis")
                        .WithMany()
                        .HasForeignKey("ReportThesisId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsReportThesis")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsReviews", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsReviews")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsScientificConsultations", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.ScientificConsultation", "ScientificConsultation")
                        .WithMany()
                        .HasForeignKey("ScientificConsultationId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsScientificConsultations")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsScientificInternships", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.ScientificInternship", "ScientificInternship")
                        .WithMany()
                        .HasForeignKey("ScientificInternshipId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsScientificInternships")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Reports.TeacherReportsScientificWorks", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Publications.ScientificWork", "ScientificWork")
                        .WithMany()
                        .HasForeignKey("ScientificWorkId");

                    b.HasOne("ScientificReport.DAL.Entities.Reports.TeacherReport", "TeacherReport")
                        .WithMany("TeacherReportsScientificWorks")
                        .HasForeignKey("TeacherReportId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.Review", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId");

                    b.HasOne("ScientificReport.DAL.Entities.Publications.Publication", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.ScientificConsultation", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Guide")
                        .WithMany()
                        .HasForeignKey("GuideId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfile", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Department")
                        .WithMany("Staff")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesArticles", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Publications.Article", "Article")
                        .WithMany("UserProfilesArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "Author")
                        .WithMany("UserProfilesArticles")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesGrants", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Grant", "Grant")
                        .WithMany("UserProfilesGrants")
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "UserProfile")
                        .WithMany("UserProfilesGrants")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesPublications", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Publications.Publication", "Publication")
                        .WithMany("UserProfilesPublications")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "UserProfile")
                        .WithMany("UserProfilesPublications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesReportThesis", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.ReportThesis", "ReportThesis")
                        .WithMany("UserProfilesReportTheses")
                        .HasForeignKey("ReportThesisId");

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "UserProfile")
                        .WithMany("UserProfilesReportTheses")
                        .HasForeignKey("UserProfileId");
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesScientificInternships", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.ScientificInternship", "ScientificInternship")
                        .WithMany("UserProfilesScientificInternships")
                        .HasForeignKey("ScientificInternshipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "UserProfile")
                        .WithMany("UserProfilesScientificInternships")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ScientificReport.DAL.Entities.UserProfile.UserProfilesScientificWorks", b =>
                {
                    b.HasOne("ScientificReport.DAL.Entities.Publications.ScientificWork", "ScientificWork")
                        .WithMany("UserProfilesScientificWorks")
                        .HasForeignKey("ScientificWorkId");

                    b.HasOne("ScientificReport.DAL.Entities.UserProfile.UserProfile", "UserProfile")
                        .WithMany("UserProfilesScientificWorks")
                        .HasForeignKey("UserProfileId");
                });
#pragma warning restore 612, 618
        }
    }
}
